# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: '^docs'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: fix-encoding-pragma
    -   id: requirements-txt-fixer
-   repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-csslint
    rev: v1.0.5
    hooks:
    -   id: csslint
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.0.0-rc.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: eslint
        additional_dependencies:
        -   eslint@4.15.0
        -   eslint-loader@1.6.1
        -   eslint-plugin-react@6.10.3
        -   babel-eslint@6.1.2
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v4.0.0-alpha.8'  # Use the sha / tag you want to point at
    hooks:
    -   id: prettier
        types_or: [javascript]
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.3.4'
  hooks:
    - id: ruff
