name: Spinorama

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.10.12"
    - run: which python
    - run: pwd
    - run: ls -la
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        sudo apt-get install -y build-essential
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude .venv
    - name: Test metadata file
      run: |
        PYTHONPATH=src ./scripts/check_meta.py
    - name: Compilation of cython files
      run: |
        PYTHONPATH=src cd src/spinorama && python setup.py build_ext --inplace && ln -s c_compute_scores.cpython-*.so c_compute_scores.so
    - name: Test with pytest
      run: |
        pip install pytest
        PYTHONPATH=src pytest tests
