name: Spinorama Javascript

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup
      uses: actions/setup-node@v4
      with:
        node-version: '21'
        cache: 'npm'
    - name: CI
      run: npm ci
    - name: Test
      run: npm test
